### ISSUE TITLE
Extra words on the secret recovery phrase quiz

### ISSUE THREAD

**Issue by adammake** [make-software/casper-wallet#557]
The following request affects the user experience on the secret recovery phrase quiz in onboarding.

**Problem**
As you confirm words, when you submit the 5th word, the 6th word is your only word left and thus unnecessary. Like if you were playing Solitaire on the computer, you’ve reached the point where you’ve solved the game and it will auto complete now :wink: The step of confirming the 6th word is entirely redundant.
You can’t remove it, because then the 5th one becomes redundant.
**Solution**
The only way to solve it I can think of, is to add more words to the list of choices. It also increases the security. Now it’s not just about getting the right order, but also the right words. So maybe instead of 6 it should be a list of 12 words.
![image](https://user-images.githubusercontent.com/97249036/222154797-d1cbd089-a6ce-4949-8242-061eb7b5a0b8.png)

**Comment by karatnyk** [comment]
@piotrwitek @adammake 
Right now (build 1.3.0) almost every time I go through onboarding the 7th extra word is the one that already is in the secret phase, meaning that tickte's original problem remains: when you submit the 5th word, the last two are still unnecessary as one of them is already in the list, meaning that the other one is required to be submitted.
![chrome_x6FTp5OBly.gif](https://images.zenhubusercontent.com/6241d5bd38a85b3df1624280/2002d53f-ef55-4f2b-94bb-d73b2067a184)

So technically, this ticket is resolved since now there is an extra word, but on the other hand presence of said extra word brings no complexity to secret phrase confirmation step, meaning that the issue remains.
From my perspective this ticket requires additional development, but it's not my call, so please advise.

**Comment by piotrwitek** [comment]
@karatnyk thanks for the feedback, I agree it's not perfect right now but it works and should not be a show stopper. We should create a backlog to discuss a better solution to improve.
cc @adammake
