### ISSUE TITLE
New account info standard

### ISSUE THREAD

**Issue by piotrwitek** [make-software/casper-wallet#628]
Supersede #480

Use Michael's feedback from Slack [LINK](https://makellc.slack.com/archives/C026E4N640N/p1680912013860189) to implement the following changes to the existing account info standard implementation:
- On the home page display the user-created name instead of the AIS name
- on all accounts lists (switch, connect) display user-created name instead of the AIS name
- when using rename feature it should show and change only the user-created name
- Show the AIS name on the account details page as an additional data row

**Comment by don-truong** [comment]
(wrote a ticket but saw @piotrwitek already had it here thus I pasted in this section). I elaborateed on what is needed and added screenshots to make it clearer, overall in-line with what Piotr specified in the requirement. 

1.  Custom name: the name a user assigns to the address from the start when he creates a new account, or later by using ‘Rename’ function. This name is for personal/internal use and is NOT visible to external parties. Assigning name is especially helpful to users with more than one account to help them navigate between accounts easier. 
2. AIS name: adhering to AIS, this name is taken from the user-defined acc metadata that was created for public/external use cases. For this reason it should be secondary to the Custom name in the CW user interface which is for personal use mostly. 

Given the above, the Custom name should be the DEFAULT name throughout CW user interface since it is for personal use, whilst AIS name should be treated as secondary information and does not need to be visible everywhere.

How to display names on CW:

1/ Home screen (”Little Lumberjack” as per attached): use custom name, NOT AIS name
![image.png](https://images.zenhubusercontent.com/63598f5c7131e92633abce8a/15d9607c-2052-49f5-a5d1-f62fc914aee3)
2/ “Account list” section (attached): use custom name, NOT AIS name
![image.png](https://images.zenhubusercontent.com/63598f5c7131e92633abce8a/4dd613c6-e980-4d02-9e99-38cb2b79e30c)
3/ “Manage” section: Display Custom name as the primary name, and AIS name as the secondary name - show the AIS as an additional row below Custom name. 
[Uploading... image.png]
4. "Connected sites” section: display Custom name, NOT account name.
![Screenshot 2023-04-17 at 13.12.58.png](https://images.zenhubusercontent.com/63598f5c7131e92633abce8a/f4feae00-8531-483a-93b6-5cb939a405a8)
